### ISSUE TITLE
Send discovery packet manually

### ISSUE THREAD

**Issue by sbcarp** [plasticrake/tplink-smarthome-api#100]
Is it possible to send discovery packet manually?
The default discoveryInterval is 10s, I think it's good enough for normal use, but I want to send the packet immediately after calling setPowerState to devices, so that it will detect power state changes as soon as possible.
Thanks!

**Comment by plasticrake** [comment]
if you're using setPowerState it already fires the event for the state change immediately. It doesn't have to wait for discovery. Also any time the state is queried (getPowerState, getSysInfo, getInfo etc), it will refire events for state change, you don't need to wait for discovery. I'm not certain sending discovery manually is needed.

**Comment by sbcarp** [comment]
I have the api client running on two machines, A and B.


> if you're using setPowerState it already fires the event for the state change immediately. It doesn't have to wait for discovery. Also any time the state is queried (getPowerState, getSysInfo, getInfo etc), it will refire events for state change, you don't need to wait for discovery. I'm not certain sending discovery manually is needed.

I figured it out, thanks!
