### ISSUE TITLE
Any plans to add Tapo P100 plug support?

### ISSUE THREAD

**Issue by bigandy** [plasticrake/tplink-smarthome-api#112]
Hi, I am unable to use with my Tapo P100 plugs, do you have any plans to support these? I am experiencing the same issues as in https://github.com/plasticrake/tplink-smarthome-api/issues/103 Thanks, Andrew

**Comment by bigandy** [comment]
Looks like there is a python implementation https://github.com/K4CZP3R/tapo-p100-python

**Comment by Xeonzinc** [comment]
I would second a request for support of the P100 if it is being considered, they are more cost effective for large installations and seem to be quite popular

**Comment by ToXIc-Dev** [comment]
While I would also love to see it.

The tapo plugs would need a different approach to how you interact with them as you need to be authenticated, the API that @bigandy posted works but needs your tp link account and password.

**Comment by Xeonzinc** [comment]
From what I've read tapo it's basically just a competitor they bought out, hence the entirely different app etc... I havn't seen anything about if they are going to join up the two approaches at some point 🙄

**Comment by Xeonzinc** [comment]
FYI There seem to be a couple of people looking at node js implementations for P100 - although they appear to be WIP and I haven't managed to successfully use either fully yet (device list seems to work fine on #1, but cant switch on/off).

[https://www.npmjs.com/package/tp-link-tapo-connect](https://www.npmjs.com/package/tp-link-tapo-connect)
[https://www.npmjs.com/package/homebridge-tapo](https://www.npmjs.com/package/homebridge-tapo)

**Comment by Xeonzinc** [comment]
UPDATE - The github version of tp-link-tapo-connect has had a quick fix and now works well for turning on and off the P100 smart plugs (doesn't quite seem fully linked to the npm version yet)

[https://github.com/dickydoouk/tp-link-tapo-connect](https://github.com/dickydoouk/tp-link-tapo-connect)

**Comment by bigandy** [comment]
> UPDATE - The github version of tp-link-tapo-connect has had a quick fix and now works well for turning on and off the P100 smart plugs (doesn't quite seem fully linked to the npm version yet)
> 
> https://github.com/dickydoouk/tp-link-tapo-connect

wow great this is just what I was after thanks @Xeonzinc (and @dickydoouk for creating it)

**Comment by plasticrake** [comment]
I don't plan on support Tapo since its a completely different communication protocol
