### ISSUE TITLE
Support Smart Actions?

### ISSUE THREAD

**Issue by simlu** [plasticrake/tplink-smarthome-api#122]
I'm intrigued by smart actions... somehow they configure devices to broadcast some (?) state changes, which would be super helpful to prevent excessing polling.

Is this something that should be supported in this library? Anyone looked at smart actions and how they work yet?

Cheers and this is an awesome library btw! L~

**Comment by plasticrake** [comment]
I think this requires a tplink hub to manage and is probably beyond the scope of this project. I think it may also use tplink cloud to configure rather than local control and this project is focused on local control vs cloud.
