### ISSUE TITLE
without any app install ?

### ISSUE THREAD

**Issue by gedw99** [plasticrake/tplink-smarthome-api#144]
Hey @plasticrake Newbie question ... 

Can this golang lib allow me to run this on a raspi ( for example ) and NOT need to install their stupid app from tp link ?

I need to install a ton of e27 tp link bulbs and LED strips, and just want a web gui for controlling them that i can run on our mobiles at home.

**Comment by plasticrake** [comment]
This isn't a golang lib, and its not a web gui. This is a node API.
