### ISSUE TITLE
Editing Schedules

### ISSUE THREAD

**Issue by bdebmport** [plasticrake/tplink-smarthome-api#165]
Can you actually edit schedule rules with this? I've worked through the examples, documentation, Googled, ChatGPTed, and watched JS tutorials endlessly and can't get anywhere. Thanks!

**Comment by plasticrake** [comment]
They can be annoying as different devices can have different parameter syntaxes, but you can see examples in the tests. I've tested these against some real devices in the past:

https://github.com/plasticrake/tplink-smarthome-api/blob/33f55531e6d5935d57a065fb95fa5dc340c4f392/test/shared/schedule.js

**Comment by plasticrake** [comment]
Closing as this isn't an issue. There is a discussions section you can also use.
