### ISSUE TITLE
Crashes after ~12h

### ISSUE THREAD

**Issue by dersimn** [plasticrake/tplink-smarthome-api#17]
Using the script for: https://github.com/dersimn/HS100toMQTT
causes my Mac Mini to crash after about 12h, when polling every second.  
No connections to the machine work after that, probably because all ports are kinda used up to open new connections (or still in some reserved state).  

This might occur just on my machine anyway, but probably you could consider to leave the socket connection open for each device and re-use it for communication. Currently you're opening a TCP socket connection, make a request and close it immediately after.

My suggestion would be to implement an idle timer that is reset on every message send/receive, if no message occours for a given time (maybe around ~2mins) the socket connection will be closed.

**Comment by plasticrake** [comment]
This is the first I've heard of an issue like this. I know I run hs100-api constantly polling a few devices for days at a time with no issue (also on a mac mini). Are you saying your mac mini is crashing or the program? Do you have any error messages?

**Comment by dersimn** [comment]
You and me both.. but it seems like all TCP ports from some kind of pool are getting used up, so that it can't assign a free one to incoming clients anymore. Many Application that are using network streams won't work until a restart.

The node script itself stops working (but doesn't crash, it just posts "connection timeout" errors). The computer is still usable (locally) but you can't connect to the Webserver anymore, SSH works for some strange reason, VNC not though.

**Comment by dersimn** [comment]
I'll look into this deeper once I figured out how I can `npm install` your library locally to test changes. Since you started to use this `nom build` thing, this [here](https://github.com/dersimn/HS100toMQTT/commit/e49a8ce23c5956bc69d269a7103c954975a17ce5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) doesn't work anymore

**Comment by plasticrake** [comment]
This library has [automated testing](https://travis-ci.org/plasticrake/hs100-api) and is used by other apps just fine. As long as you are on at least node v4 and npm v3 you should be able to run `npm install` or `npm run build` and `npm test`. If you want to point your app to your local copy you can use `npm link` ([see here](https://docs.npmjs.com/cli/link))

**Comment by dersimn** [comment]
It's really strange..
Works perfectly on a Raspberry for >48h now. Even within Docker on a Raspberry.

**Comment by plasticrake** [comment]
Glad it seems to be working better. I'm going to close this issue. If you have any further problems please submit a new issue. Thanks!
