### ISSUE TITLE
Version 0.2.0 is installed rather than version 1.0.0

### ISSUE THREAD

**Issue by Ricardo1980** [plasticrake/tplink-smarthome-api#21]
Hello,

Right now I execute:
`sudo npm install -g tplink-smarthome-api`
And I see:
```
/usr/bin/tplink-smarthome-api -> /usr/lib/node_modules/tplink-smarthome-api/lib/cli.js
+ tplink-smarthome-api@0.20.0
added 10 packages in 15.07s
```

Shouldn't the version 1 be installed?
Thanks.

**Comment by plasticrake** [comment]
There is no version 1

**Comment by plasticrake** [comment]
I just checked the changelog, I'm guessing that is the confusion, I'll update.

**Comment by Ricardo1980** [comment]
Yes, it is here:
https://github.com/plasticrake/tplink-smarthome-api/blob/master/CHANGELOG.md
