### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by tremblam** [plasticrake/tplink-smarthome-api#22]
Is there a docker image associated with this project?

**Comment by plasticrake** [comment]
No, but I'm not sure why a docker image of this would be useful. Can you explain? This is really a dependency to be used by other node applications. There is a CLI tool but its not really the main forcus of this (I made the CLI portion mostly for testing and troubleshooting)

**Comment by tremblam** [comment]
I see your point. I'm not overly familiar with node applications. I noticed that your road map had a web interface in it so thought it would be useful as an isolated webserver. 

I currently own a few Wemo devices and manage them with a few scripts and a web interface using this project in a docker container. https://github.com/iancmcc/ouimeaux . I'm looking for something to do the same with my new tp-link devices
