### ISSUE TITLE
Problem with startDiscovery

### ISSUE THREAD

**Issue by haloszymek** [plasticrake/tplink-smarthome-api#23]
Hi, I have a problem when I am trying to run example code:
```
const { Client } = require('tplink-smarthome-api');
const client = new Client();

// Look for devices, log to console, and turn them on
client.startDiscovery().on('device-new', (device) => {
  device.getSysInfo().then(console.log);
  device.setPowerState(true);
});
```
I am connected to the same network with TP-LINK_Smart Plug_XXXX. The script starts but nothing more happens. If I try to use CLI _search_ command, I will get: 
```
user@comp11:~$ tplink-smarthome-api -D search
Searching...
startDiscovery({ discoveryInterval: 2000, discoveryTimeout: 5000 })
client.startDiscovery({"discoveryInterval":2000,"discoveryTimeout":5000})
client.socket: UDP IPv4 listening on 0.0.0.0:59295
client.sendDiscovery("255.255.255.255")
client.sendDiscovery("255.255.255.255")
client.sendDiscovery("255.255.255.255")
client.startDiscovery: discoveryTimeout reached, stopping discovery
client.stopDiscovery()
```

What can go wrong? Any additional options are required?

**Comment by plasticrake** [comment]
Did you setup your device in the Kasa app?

**Comment by haloszymek** [comment]
It seems like my firewall was blocking all upcoming broadcast responses. Solution is to change firewall rules.

**Comment by jimmykl** [comment]
@haloszymek I have the same problem but afaik don't have any firewall rules effecting port the ports tplink-smarthome-api is using, could you explain how you unblocked broadcast responses?
