### ISSUE TITLE
After 1 day of uptime, HomeKit will stop turning on/off to link devices

### ISSUE THREAD

**Issue by TylerD89** [plasticrake/tplink-smarthome-api#24]
So I have this installed my my raspberry pi running the latest version of Homebridge and to tplink-smarthome-api. After one day (usually when I wake up), I can not turn on/off tplink devices. 

So when this happens: 
In the homekit app, I can tap on the devices and they will act like they turn on (it will say “on” and turn white), but the actual start device itself will stay off. 
Any fix for this?

**Comment by TylerD89** [comment]
They only way to resolve this issue is to restart the entire Raspberry Pi. Restarting the Homebridge service won’t solve it... weird

**Comment by plasticrake** [comment]
@TylerD89 Did you mean to submit this to [homebridge-tplink-smarthome](https://github.com/plasticrake/homebridge-tplink-smarthome) instead?

**Comment by TylerD89** [comment]
Yes haha. Oops, that’s a little embarrassing. Sorry about that
