### ISSUE TITLE
Instructions - how to

### ISSUE THREAD

**Issue by akfaulkner** [plasticrake/tplink-smarthome-api#25]
Hi

This looks great!  Do you have any instructions from start to finish on how to use this with the tp-link smart plug?  I just want to try a little project and want to make sure I setup the plug and environment up correctly and I didn't see any instructions on setup.

Thank you!

**Comment by plasticrake** [comment]
There are simples examples in the example folder. What exactly are you looking for?

**Comment by salkin90** [comment]
Could you please explain how to use the cli tool to send on/off commands to the hs110?
I assume you use sendCommand, but with which payload?

Thank you!

**Comment by dhinadhinesh007** [comment]
Hi,

Yes, even I have a similar question. I just bought a new HS110 plug and I want to experiment it with this API. How do I start? I am very new to node js. If you could just tell me how to access the data from a php script it will be really helpful.  I was able to find out the functions like getsysinfo, getpowerstate, etc from the documentation. But I could not figure out how to execute them.

Kindly help.

**Comment by GeertvanWissen** [comment]
I was looking for a type of Wifi connected light bulb to work with my own, self created domotics system running on a raspberry pi. I do NOT want to work with proprietary cloud services. Based on your api, the TP-link bulb looks like the right choice. Is these any support for this kind of control from TP-link themselfs, or is there a chance they will change the security model and this api will get deprecated?

**Comment by plasticrake** [comment]
@dhinadhinesh007 This is a node api and not for PHP. You may be able to find a way to use it but I can't help you.

@GeertvanWissen As far as I know this is an unsupported API. It was reversed engineered from using the TPLink Kasa app. It may be stable but that is not guaranteed.
