### ISSUE TITLE
throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);

### ISSUE THREAD

**Issue by r32er** [plasticrake/tplink-smarthome-api#26]
hey,

first i have installed the plugin https://www.npmjs.com/package/homebridge-hs100
but when i had read the plugin was renamed and i have to install this plugin instead.

now i get the error up there. i had remove the persist and accesories folder but it don't help..

my config:

                {
                        "platform": "TplinkSmarthome",
                        "name": "TplinkSmarthome"
                },

**Comment by plasticrake** [comment]
I think you meant to post this in [homebridge-tplink-smarthome](https://github.com/plasticrake/homebridge-tplink-smarthome). If you're still having issues please post there. Although what you're describing sounds like removing the accesssories folder should fix. Can you try again? If you're still having problems please submit in the other repo and fill out the issue template and include the log output.

**Comment by r32er** [comment]
you are right. sorry my fault. yes i mean https://github.com/plasticrake/homebridge-tplink-smarthome

**Comment by plasticrake** [comment]
You need to delete the file on your computer. 

`rm -rf ~/.homebridge/accessories`

https://github.com/plasticrake/homebridge-tplink-smarthome#uuid-errors
