### ISSUE TITLE
win10 search not work

### ISSUE THREAD

**Issue by arteck** [plasticrake/tplink-smarthome-api#27]
the search function dont work on win10 .. on Pi3 without problems.. 

Searching...
startDiscovery({ discoveryInterval: 2000, discoveryTimeout: 5000 })
client.startDiscovery({"discoveryInterval":2000,"discoveryTimeout":5000})
client.socket: UDP IPv4 listening on 0.0.0.0:50884
client.sendDiscovery("255.255.255.255")
client.sendDiscovery("255.255.255.255")
client.sendDiscovery("255.255.255.255")
client.startDiscovery: discoveryTimeout reached, stopping discovery
client.stopDiscovery()

**Comment by plasticrake** [comment]
I don't have a windows machine, however I just borrowed a friends windows 10 PC and it was working fine. Perhaps something else is different on your network?

```
Your environment has been set up for using Node.js 8.9.3 (x64) and npm.

C:\Users\Patrick>npm install -g tplink-smarthome-api
C:\Users\Patrick\AppData\Roaming\npm\tplink-smarthome-api -> C:\Users\Patrick\AppData\Roaming\npm\node_modules\tplink-smarthome-api\lib\cli.js
+ tplink-smarthome-api@0.20.1
added 10 packages in 32.869s

C:\Users\Patrick>tplink-smarthome-api search
Searching...
startDiscovery({ discoveryInterval: 2000, discoveryTimeout: 5000 })
HS105(US) plug IOT.SMARTPLUGSWITCH 10.0.0.109 9999 <> Bathroom Fan
HS110(US) plug IOT.SMARTPLUGSWITCH 10.0.0.119 9999 <> Test
HS100(US) plug IOT.SMARTPLUGSWITCH 10.0.0.118 9999 <> Living Room Fan
HS100(US) plug IOT.SMARTPLUGSWITCH 10.0.0.116 9999 <> Bedroom Fan
LB130(US) bulb IOT.SMARTBULB 10.0.0.101 9999 <> My Smart Bulb
```
