### ISSUE TITLE
no data from HS110

### ISSUE THREAD

**Issue by arteck** [plasticrake/tplink-smarthome-api#28]
i see no data from emeter request.. 

"get emeterRealtime" is in sourcecode disabled.. ??

tplink-smarthome-api getInfo 192.168.x.x work 
emeter:
   { realtime:
      { current: 0.01185,
        voltage: 235.51043,
        power: 0,
        total: 5.472,
        err_code: 0 } },

but 
```
client.getDevice({host: ip}).then((result) => {
  var meter = result.emeter.realtime;
 });
```
not

**Comment by plasticrake** [comment]
emeter.realtime has the last cached value, but you never retrieved it.

It returns a promise. so you need to do: `result.emeter.getRealtime.then((result) => { console.log(result) })`

**Comment by arteck** [comment]
very nice...thx
