### ISSUE TITLE
.startDiscovery only works once

### ISSUE THREAD

**Issue by alwynallan** [plasticrake/tplink-smarthome-api#31]
I'm new to node.js so I might be missing something obvious. I would expect that I could instantiate a global client:
`var client = new Client();`
and then perform a repeated sequence of
`client.startDiscovery();`
`...`
`client.stopDiscovery();`
but only the first time gets any events. It can be worked around by starting a new client each time.

BTW, thanks for the awesome library. I liked the Kasa line before, but now I LOVE it.

**Comment by plasticrake** [comment]
Hi, sorry I'm not quite following the issue. I use startDiscovery myself and it definitely queries the devices on an interval and causes the client to emit events. I don't have to call it multiple times. There are even test scripts that show this behavior. If you share the code with the issue I may be able to look.

**Comment by alwynallan** [comment]
The function bulb_page() in
https://github.com/alwynallan/sunrise/blob/master/master.js uses
startDiscovery() to list the available color bulbs. Nothing stops two users
from calling the page at the same time, and the function should have a
local instance of  'client' to allow this, but it doesn't work.

I haven't seen a real-work problem yet, but with caching and pre-fetching
and search-engine spidering you don't really know who's loading a page.

Thanks!

A. Peter Allan · 450 Timber Lane · Devon PA 19333 · 610-687-1708 ·
610-547-4836 mobile

**Comment by plasticrake** [comment]
`bulb-new` is only emitted once per bulb, it is to find new bulbs. If you're trying to monitor updates to existing bulbs check out the other events such as `bulb-online`
