### ISSUE TITLE
WATT

### ISSUE THREAD

**Issue by croziors** [plasticrake/tplink-smarthome-api#37]
Hello it s possible have WATT  with just number not
Power ...... ( with color) :  230.34W ??

**Comment by plasticrake** [comment]
I'm not sure what you're asking, but the API here fetches exactly what is returned from the device. You can format it however you like

**Comment by croziors** [comment]
i dont  know how format i want just number  power watt 
command return just 203.22   not return Power ... 303.22 W

**Comment by croziors** [comment]
![image](https://user-images.githubusercontent.com/19520104/34909739-3c04cbce-f8a7-11e7-9975-ed68ff0255ce.png)

i want just number with not color

**Comment by plasticrake** [comment]
This is primarily a node API project. The command line app is really for testing. You may find a better project if all you want is a command line tool. You can easily do what you request if you write a short node app and use the API. I can't help you with parsing the output of the command line.
