### ISSUE TITLE
Error: Cannot find module '..'

### ISSUE THREAD

**Issue by jimmykl** [plasticrake/tplink-smarthome-api#42]
I have a script working on my mac but when I put it on a raspberry pi I get the error ```Error: Cannot find module '..'``` (it's located in the examples folder)

I'm a node newbie so I'm sure this is a simple fix but how can I resolve this?

**Comment by jimmykl** [comment]
Guess I should say the script is located in the examples folder and I installed the api with ```npm install -g tplink-smarthome-api```

**Comment by jimmykl** [comment]
Solved: used module.paths and saw the raspberry pi install was using /usr/local/lib/node which didn't exist so fixed with ```ln -s /usr/local/lib/node_modules/ /usr/local/lib/node```

**Comment by dmitridr** [comment]
Just wanted to say thanks for this. Had the same problem, this is the only result via search.
The pi was using `/usr/lib/node` for me so I did something similar:

`ln -s /usr/local/lib/node_modules/ /usr/lib/node`

It worked.
