### ISSUE TITLE
Device IP address

### ISSUE THREAD

**Issue by haloszymek** [plasticrake/tplink-smarthome-api#45]
Using `tplink-smarthome-api search`in terminal I get `HS100(EU) plug IOT.SMARTPLUGSWITCH 192.168.0.248 9999 <<long_number_of_device_id>> SmartLamp` with IP address 192.168.0.248. startDiscovery do not return any information about IP. How can I get it?

**Comment by slametps** [comment]
You can access IP and PORT for each detected devices as following:
```
client.startDiscovery(commandParams)
        .on('device-new', (device) => {
          console.log(`${device.model} ${device.deviceType} ${device.type} ${device.host} ${device.port} ${device.deviceId} ${device.alias}`);
});
```

**Comment by haloszymek** [comment]
Thank you!
