### ISSUE TITLE
Cant Execute On/Off from Command Line

### ISSUE THREAD

**Issue by gmola** [plasticrake/tplink-smarthome-api#46]
Hi I'm trying to test the execution of this command but see no action on the light and no output is returned.
tplink-smarthome-api send 111.111.11.1 '{"plug":{"power-on"}}'

Can you verify I'm structuring the command correctly?

Thanks,
Giovanni

**Comment by AllenW1** [comment]
I have the same problem and have tried many combinations of
tplink-smarthome-api -D send <HS100 IP>:9999 <payload>
e.g.
tplink-smarthome-api -D send 192.168.1.128:9999 '{"system":{"set_relay_state=true"}}'
tplink-smarthome-api -D send 192.168.1.128:9999 '{"system":{"set_relay_state=1"}}'
tplink-smarthome-api -D send 192.168.1.128:9999 '{"system":{"set_relay_state=on"}}'
The -D option has been helpful to see this and other commands work (like blink). No error comes back. I have no luck guessing the right syntax in this send case.
I have tried various <payload> syntax for the sendCommand command as well.
I wish the documentation provided specifics on the arguments the varius commands require.
I welcome any insights.

**Comment by AnthonyHarwood** [comment]
I've had success with both
tplink-smarthome-api send 192.168.1.128:9999 '{"system":{"set_relay_state":{"state":1}}}'
and
tplink-smarthome-api sendCommand 192.168.1.128:9999 '{"system":{"set_relay_state":{"state":1}}}'

**Comment by The009** [comment]
@AnthonyHarwood I have tried both those and many others just as @AllenW1 has. I keep getting the following. With no switches doing anything :(


G:\Devolupment\Node\tplink-smarthome-api-0.22.0\examples
? tplink-smarthome-api send 10.0.0.178 '{“system":{"set_relay_state":{"state":1}}}'
Sending to 10.0.0.178:undefined...

G:\Devolupment\Node\tplink-smarthome-api-0.22.0\?
 tplink-smarthome-api send 10.0.0.178:9999 '{“system":{"set_relay_state":{"state":1}}}'
Sending to 10.0.0.178:9999...

G:\Devolupment\Node\tplink-smarthome-api-0.22.0\?
tplink-smarthome-api sendCommand 10.0.0.178:9999 '{“system":{"set_relay_state":{"state":1}}}'
Sending to 10.0.0.178:9999...
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Plug._callee2$ (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\lib\device\index.js:241:92)
    at tryCatch (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\core-js\library\modules\_export.js:36:28)
    at C:\Users\User\AppData\Roaming\npm\node_modules\tplink-smarthome-api\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12

**Comment by plasticrake** [comment]
This repo is for a Node API. There is a command line tool I created just to help testing, but its not the primary function of this. You can do what you're asking by writing a very small node script. See example: [plug-turn-on-off.js](https://github.com/plasticrake/tplink-smarthome-api/blob/master/examples/plug-turn-on-off.js)

The relevant command is [here:](https://github.com/plasticrake/tplink-smarthome-api/blob/6e2551be07c231017887e9652c935a058af485bc/src/plug/index.js#L246)
```js
await this.sendCommand(`{"system":{"set_relay_state":{"state":${(value ? 1 : 0)}}}}`, sendOptions);`
```

**Comment by AnthonyHarwood** [comment]
@The009 it looks like there is a problem with one of your quotation marks.

Check your json and look before the word system.  It appears you are using the “fancy” quotes instead of the regular quotes.

I hope this resolves your problem.
