### ISSUE TITLE
Include realtime meter in getInfo()

### ISSUE THREAD

**Issue by adreno369** [plasticrake/tplink-smarthome-api#48]
**What**
`getInfo()` object of bulbs *(I don't know about plugs)* lacks the realtime info about device consumption.

**Why**
I maintain a repo. of a Node-RED's node and I use the output of `getInfo()` to populate gauges and other nice things on a UI *(temperature, intensity, etc.)*. The problem is that if I want to get the meter, I don't have a propriety in `payload` to target and every time I pull the info for the gauge, I get the error of undefined from the `getInfo()` and vice-versa *(because I use 2 inputs and 2 outputs that listen to different things)*. It would be cleaner.

**Reference**
mental05/node-red-contrib-tplink-iot#3

**Comment by plasticrake** [comment]
`getInfo()` does retrieve `"emeter":{"get_realtime":{}}` for both bulbs and plugs. I tested it against one of my LB130s and it returns the data. If you're having an issue please provide some more info.
