### ISSUE TITLE
Has anyone tried this api with a HS220 switch?

### ISSUE THREAD

**Issue by soluml** [plasticrake/tplink-smarthome-api#49]
I've used this API with the LB130 and the HS105 with great results and was looking into replacing some of my dimmers.  Has anyone tried this with the HS220?

**Comment by timcharper** [comment]
Sending a dimmer value should be really easy. I think an easy way to contribute here would be to figure out the protocol, first. I'm sure it's a simple extra JSON field for "brightness". I don't have any HS220 devices. If someone wants to send me one, I'll implement support for it! :)

**Comment by soluml** [comment]
Yea, I'm sure they have a similar contract to the other devices.  I don't mind getting my hands dirty, so I'll PR if I come up with anything :)

**Comment by plasticrake** [comment]
@solumi Any luck? If you find any other software that supports this I can possibly port it here. You can also monitor the commands that are sent via the Kasa app to reverse engineer the commands using wireshark.

**Comment by soluml** [comment]
@plasticrake haven't purchased one yet. Still planning on it at some point, was just waiting to score a deal. Will definitely PR anything I figure out when I do.

**Comment by soluml** [comment]
With the deals over the weekend I finally got around to picking up and installing an HS220.  Configured it with the app and updated the firmware.  After playing around tonight, I'm able to confirm that discovery picks up the device fine and I'm able to turn the power on via `setPowerState`.  

I'll be doing some more playing around later this week, but it looks like HS220 works out of the box!

**Comment by timcharper** [comment]
I was able to figure it out today. The following command sets the brightness:

```
15:00 $ node lib/cli.js send 192.168.2.4 '{"system":{"set_relay_state":{"state":1}},"smartlife.iot.dimmer":{"set_brightness":{"brightness":100}}}'
Sending to 192.168.2.4:undefined...
response:
{ system: { set_relay_state: { err_code: 0 } },
  'smartlife.iot.dimmer': { set_brightness: { err_code: 0 } } }
```

Brightness is 0-100. Either value can be supplied.

To get this, I set up my mac as a wireless access point and connected my mobile phone and my dimmer switch to it. Then I installed the dissector available here: https://raw.githubusercontent.com/softScheck/tplink-smartplug/master/tplink-smarthome.lua

Then, I went in to the switch in the kasa app, and clicked on one of the presets. Presto.

**Comment by plasticrake** [comment]
Thanks @timcharper! I should be able to work with that. Can you or anyone else with one of these devices run the following command and post the output here? Feel free to remove any sensitive data such as location info.

`tplink-smarthome-api getSysInfo <ip here>`

**Comment by timcharper** [comment]
Here's some other commands and notes and things.


Start test calibration:

```
{"smartlife.iot.dimmer":{"test_dimmer_calibration":{"delay":1000,"duration":3000}}}
```


# Gentle on off

Turn off slowly over 5 seconds:

```
{"smartlife.iot.dimmer":{"set_dimmer_transition":{"brightness":0,"mode":"gentle_on_off","duration":5}}}'
```

Turn on slowly over 1 seconds:

```
{"smartlife.iot.dimmer":{"set_dimmer_transition":{"brightness":100,"mode":"gentle_on_off","duration":1}}}
```


# Configuration:

Read config:

```
{"smartlife.iot.dimmer":{"get_default_behavior":{}}}

// response
{"smartlife.iot.dimmer":{"get_default_behavior":{"soft_on":{"mode":"last_status"},"hard_on":{"mode":"last_status"},"long_press":{"mode":"instant_on_off"},"double_click":{"mode":"gentle_on_off"},"err_code":0}}}
```

Set gentle off time:

```
{"smartlife.iot.dimmer":{"set_gentle_off_time":{"duration":30000}}}
```



Set double click action:

```
{"smartlife.iot.dimmer":{"set_double_click_action":{"mode":"none"}}}
{"smartlife.iot.dimmer":{"set_double_click_action":{"mode":"instant_on_off"}}}
{"smartlife.iot.dimmer":{"set_double_click_action":{"mode":"gentle_on_off"}}}
{"smartlife.iot.dimmer":{"set_double_click_action":{"mode":"customize_preset","index":2}}}

```

Set long press action:

```
{"smartlife.iot.dimmer":{"set_long_press_action":{"mode":"gentle_on_off"}}}
{"smartlife.iot.dimmer":{"set_long_press_action":{"mode":"customize_preset","index":2}}}
{"smartlife.iot.dimmer":{"set_long_press_action":{"mode":"instant_on_off"}}}
{"smartlife.iot.dimmer":{"set_long_press_action":{"mode":"none"}}}
```

Set fade on speed

```

// slow
{"smartlife.iot.dimmer":{"set_fade_on_time":{"fadeTime":3000}}}

// medium
{"smartlife.iot.dimmer":{"set_fade_on_time":{"fadeTime":2000}}}

// fast
{"smartlife.iot.dimmer":{"set_fade_on_time":{"fadeTime":1000}}}

// instant
{"smartlife.iot.dimmer":{"set_fade_on_time":{"fadeTime":500}}}
```

Set fade off speed

```
// medium
{"smartlife.iot.dimmer":{"set_fade_off_time":{"fadeTime":2000}}}

// etc
```

Edit preset (index 0 - 3):

```
{"smartlife.iot.dimmer":{"set_preferred_state":{"brightness":67,"index":0}}}
```

# Rules

Set my dimmer to last on state every Tuesday at 17:38

```
{"schedule":{"add_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":1,"emin":-1,"day":9,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"enable":1,"wday":[0,0,1,0,0,0,0]}}}
{"schedule":{"edit_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":1,"emin":-1,"day":10,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"id":"7F8A95D1F2A5EC0C9F9BA448168442BF","enable":1,"wday":[0,0,1,0,0,0,0]}}}
```

Edit aforementioned rule to turn the light off:

```
{"schedule":{"edit_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":0,"emin":-1,"day":10,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"id":"7F8A95D1F2A5EC0C9F9BA448168442BF","enable":1,"wday":[0,0,1,0,0,0,0]}}}
{"schedule":{"edit_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":0,"emin":-1,"day":10,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"id":"7F8A95D1F2A5EC0C9F9BA448168442BF","enable":1,"wday":[0,0,1,0,0,0,0]}}}
```

Edit aforementioned rule to dim the turn the brightness to 54:

```
 {"schedule":{"edit_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":3,"emin":-1,"day":10,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"s_dimmer":{"on_off":1,"brightness":54,"transition_period":1000},"id":"7F8A95D1F2A5EC0C9F9BA448168442BF","enable":1,"wday":[0,0,1,0,0,0,0]}}}
{"schedule":{"edit_rule":{"smin":1058,"year":2018,"name":"name","etime_opt":-1,"sact":3,"emin":-1,"day":10,"eact":-1,"stime_opt":0,"repeat":1,"month":12,"s_dimmer":{"on_off":1,"brightness":54,"transition_period":1000},"id":"7F8A95D1F2A5EC0C9F9BA448168442BF","enable":1,"wday":[0,0,1,0,0,0,0]}}}
```

**Comment by timcharper** [comment]
@plasticrake here's the getSysInfo response:

```
18:12 $ node lib/cli.js getSysInfo 192.168.2.4
Sending getSysInfo command to 192.168.2.4:undefined...
response:
{ sw_ver: '1.5.7 Build 180912 Rel.104837',
  hw_ver: '1.0',
  mic_type: 'IOT.SMARTPLUGSWITCH',
  model: 'HS220(US)',
  mac: '0C:xx:xx:xx:xx:xxx,
  dev_name: 'Smart Wi-Fi Dimmer',
  alias: 'My Smart Dimmer',
  relay_state: 1,
  brightness: 25,
  on_time: 2673,
  active_mode: 'count_down',
  feature: 'TIM',
  updating: 0,
  icon_hash: '',
  rssi: -64,
  led_off: 0,
  longitude_i: -1118921,
  latitude_i: 403114,
  hwId: '84DCCF37225C9E55319617F7D5C095BD',
  fwId: '00000000000000000000000000000000',
  deviceId: '8006xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  oemId: '3B13224B2807E0D48A9DD06EBD344CD6',
  preferred_state:
   [ { index: 0, brightness: 100 },
     { index: 1, brightness: 75 },
     { index: 2, brightness: 50 },
     { index: 3, brightness: 25 } ],
  next_action:
   { type: 2,
     id: '3E06C287B68BBC03C24DC054A1246399',
     schd_time: 67288,
     action: 1 },
  err_code: 0 }
```

**Comment by timcharper** [comment]
Oh geez someone already had figured a lot of this out :) https://community.openhab.org/t/tp-link-dimmer-switch-binding/42192/16

**Comment by plasticrake** [comment]
@timcharper Thanks for the info! I've created a device simulator to help me test devices, especially ones I don't own. With your details I have a mock device setup that I can see and inspect in the Kasa app.

Since I don't have a physical device, I don't know the actual behavior of the device. Can you tell me what happens when `set_relay_state` is called with 1 and 0? Does the light instantly turn on/off or does it have a fade in/out?

I also maintain a homekit plugin for these devices and I'd like to know the best way to turn it on/off by default, and I assume a quick soft fade would be the preferred behavior.

**Comment by timcharper** [comment]
@plasticrake DM me your address and I'll buy you one :) I've benefitted a ton from your work.

**Comment by timcharper** [comment]
But to answer your question, `set_relay_state` triggers a transition per the configured fade speed (`set_fade_on_time`, `set_fade_off_time`, respectively)

**Comment by Austinthemighty** [comment]
Tp link does have a repository for there code on there main site
https://www.tp-link.com/us/support/gpl-code-center
