### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by deep9** [plasticrake/tplink-smarthome-api#54]
This is more a question than an issue.
Just received a new HS110 Plug and tried to discover the device, hoping for some response/getting an IP address, etc.

I see that the broadcast packet is being sent to the 255.255.255.255:9999, but no response is ever returned.

I have tried sending the discovery on the TPLINK wifi, on a regular wifi also (both devices on the same network).

I can control the device using api calls, turning the power on/off, getting info, etc.

Is there something I'm doing wrong? Or what is the correct way of using discover?

Thank you for any help.

**Comment by arteck** [comment]
i no undastand you question .. you have connected the device with you wifi ?? and you have a ip address ??
when YES open the adapter and change the ip address here

**Comment by plasticrake** [comment]
Hi @deep9, the discovery does work for most users. However some people report that it doesn't work for them. Some users have said that rebooting the router may help or you may want to check your router settings or your local PC firewall.

**Comment by plasticrake** [comment]
One other thing you may want to try is tweaking the broadcast address.  It defaults to 255.255.255.255, but if all your devices are on 192.168.0.* for example set it to 192.168.0.255

`client.startDiscovery('192.168.0.255')`

**Comment by deep9** [comment]
@plasticrake Thanks for the advice. Running the discovery only on the local part of the network actually worked.

**Comment by timcharper** [comment]
@deep9 might be nice to contribute to the README :)

**Comment by bradwbradw** [comment]
`client.startDiscovery('192.168.0.255')` doesn't change from the default of `255.255.255.255`

The correct syntax is :
```
client.startDiscovery({
      broadcast:"192.168.0.255"
      })
```

Anyway, why not make `192.168.0.255` the default, if that's how most networks are configured?

**Comment by fcastilloec** [comment]
After trying to figure out why my setup wasn't working, especially for people behind a firewall, you should also set a port number and open that port in your firewall. Adding to @bradwbradw example:

```js
client.startDiscovery({
  broadcast: '192.168.0.255',
  port: 56888
})
```

Then open port 56888 (or any other number you've set) for incoming messages on UDP in your firewall.

**Comment by simlu** [comment]
Man, that should definitely be in the readme!! Thank you @fcastilloec
