### ISSUE TITLE
Looking for deviceOptions, can't seem to find them.

### ISSUE THREAD

**Issue by LamboCreeper** [plasticrake/tplink-smarthome-api#55]
Hi, I'm looking for the `deviceOptions` that can be passed through `client.getPlug()`. However, the [page](https://github.com/plasticrake/tplink-smarthome-api/blob/master/Plug#constructor) which I believe should list them returns an error 404.

Could you please fix this as it would be a great help.

**Comment by plasticrake** [comment]
Hmm, I will have to look into how the documentation is being generated, those are supposed to be anchors to the same document, there aren't multiple pages of documentation. Just search the page for what you're looking for.

https://github.com/plasticrake/tplink-smarthome-api/blob/master/API.md#new-deviceoptions
https://github.com/plasticrake/tplink-smarthome-api/blob/master/API.md#new-plugoptions

**Comment by LamboCreeper** [comment]
Thank you!
