### ISSUE TITLE
How to get KL120 added to the supported devices list

### ISSUE THREAD

**Issue by AdrianKoshka** [plasticrake/tplink-smarthome-api#74]
I recently bought a KL120 smart bulb and was wondering how to get it added to the supported devices list.

If I run `tplink-smarthome-api details`, I get (if the deviceId is needed, I can add it, just redacted it because idk how privacy related it is):

```
{ alias: 'Bedside Lamp',
  deviceId: '<redacted>',
  description: 'Smart Wi-Fi LED Bulb with Tunable White Light',
  model: 'KL120(US)',
  deviceType: 'bulb',
  type: 'IOT.SMARTBULB',
  softwareVersion: '1.8.6 Build 180809 Rel.091659',
  hardwareVersion: '1.0',
  mac: '<redacted>' }
```

**Comment by plasticrake** [comment]
I've added KL120 to the readme list of supported devices. Thanks!
