### ISSUE TITLE
Example for Bulb Control

### ISSUE THREAD

**Issue by theryecatcher** [plasticrake/tplink-smarthome-api#78]
Hello. 

First of all Thanks for this awesome and well documented API. It has helped me do my home control for quite some time now. I am heavily invested in TPLink devices for home control and just added a bulb to the suite of devices I own from them a LB120 to be exact. But for the love of my life I cannot figure out how would I go ahead and control the temperature and brightness of the bulb using the API. Could somebody kindly guide me with that.

Thanks.

**Comment by denverhuynh** [comment]
If you're looking for the cli command, does this work for you?
 
`tplink-smarthome-api send <host> '{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{ "color_temp":2700, "brightness":100 }}}'`
