### ISSUE TITLE
Kasa smart wifi outdoor plug kp400 is supported?

### ISSUE THREAD

**Issue by thierryc** [plasticrake/tplink-smarthome-api#87]
The Kasa Smart Outdoor Plug with 2 Outlets, Individual Control, IP64 Waterproof and Scheduling (Sunrise & Sunset), Works with Alexa & Google Home (KP400) is supported?

Item model number | KP400

https://www.kasasmart.com/us/products/smart-plugs/kasa-smart-wifi-outdoor-plug-kp400

best.

**Comment by Trakkasure** [comment]
I also would like to know. I just picked one up. If I have time over the next few weeks, I'll try to figure out something. I'm stretched pretty thin this month.

**Comment by plasticrake** [comment]
I have been told it is supported! 

plasticrake/homebridge-tplink-smarthome#85

**Comment by thierryc** [comment]
Thank you 😊
